plugins:
  - jekyll-redirect-from
theme: jekyll-theme-minimal
title: Lev Goncharov
description: Infrastructure simplifying engineer
show_downloads: false
analytics:
  provider: "google-gtag"
  google:
    tracking_id: G-KYDK0KTRF9
